artifacts_root: artifacts  # folder created for saving the data


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Bagewadinitin/ML_projects_Classification/raw/main/Wine.zip  # data file location and download
  local_data_file: artifacts/data_ingestion/data.zip  # once it download from github repo, saves it as data.zip file
  unzip_dir: artifacts/data_ingestion #unzipped file of data saved here


data_validation: 
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/WineQT.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/WineQT.csv


model_trainer: 
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib # can be also saved in pickle format

model_evaluation: 
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
