artifacts_root: artifacts  # folder created for saving the data


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Bagewadinitin/ML_projects_Classification/raw/main/Wine.zip  # data file location and download
  lacal_data_file: artifacts/data_ingestion/data.zip  # once it download from github repo, saves it as data.zip file
  unzip_dir: artifacts/data_ingestion #unzipped file of data saved here